# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bibliotheque.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bibliothequecegep(object):
    def setupUi(self, Bibliothequecegep):
        Bibliothequecegep.setObjectName("Bibliothequecegep")
        Bibliothequecegep.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Bibliothequecegep)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_lst_doc = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_lst_doc.setGeometry(QtCore.QRect(550, 250, 231, 291))
        self.textBrowser_lst_doc.setObjectName("textBrowser_lst_doc")
        self.lbl_biblio = QtWidgets.QLabel(self.centralwidget)
        self.lbl_biblio.setGeometry(QtCore.QRect(80, 0, 611, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_biblio.setFont(font)
        self.lbl_biblio.setObjectName("lbl_biblio")
        self.pushButton_ajouter_doc = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ajouter_doc.setGeometry(QtCore.QRect(100, 190, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ajouter_doc.setFont(font)
        self.pushButton_ajouter_doc.setObjectName("pushButton_ajouter_doc")
        self.pushButton_ajouter_abonner = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ajouter_abonner.setGeometry(QtCore.QRect(290, 190, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ajouter_abonner.setFont(font)
        self.pushButton_ajouter_abonner.setObjectName("pushButton_ajouter_abonner")
        self.pushButton_ajouter_doc_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ajouter_doc_3.setGeometry(QtCore.QRect(480, 190, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ajouter_doc_3.setFont(font)
        self.pushButton_ajouter_doc_3.setObjectName("pushButton_ajouter_doc_3")
        self.lbl_biblio_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_biblio_2.setGeometry(QtCore.QRect(130, 50, 611, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_biblio_2.setFont(font)
        self.lbl_biblio_2.setObjectName("lbl_biblio_2")
        self.pushButton_ajouter_abonner_ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ajouter_abonner_.setGeometry(QtCore.QRect(200, 130, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ajouter_abonner_.setFont(font)
        self.pushButton_ajouter_abonner_.setObjectName("pushButton_ajouter_abonner_")
        self.pushButton_ajouter_emprunt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ajouter_emprunt.setGeometry(QtCore.QRect(400, 130, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ajouter_emprunt.setFont(font)
        self.pushButton_ajouter_emprunt.setObjectName("pushButton_ajouter_emprunt")
        self.textBrowser_lst_abonnement = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_lst_abonnement.setGeometry(QtCore.QRect(270, 250, 231, 291))
        self.textBrowser_lst_abonnement.setObjectName("textBrowser_lst_abonnement")
        self.textBrowser_lst_emprunt = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_lst_emprunt.setGeometry(QtCore.QRect(10, 250, 231, 291))
        self.textBrowser_lst_emprunt.setObjectName("textBrowser_lst_emprunt")
        Bibliothequecegep.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Bibliothequecegep)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Bibliothequecegep.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Bibliothequecegep)
        self.statusbar.setObjectName("statusbar")
        Bibliothequecegep.setStatusBar(self.statusbar)

        self.retranslateUi(Bibliothequecegep)
        QtCore.QMetaObject.connectSlotsByName(Bibliothequecegep)

    def retranslateUi(self, Bibliothequecegep):
        _translate = QtCore.QCoreApplication.translate
        Bibliothequecegep.setWindowTitle(_translate("Bibliothequecegep", "MainWindow"))
        self.lbl_biblio.setText(_translate("Bibliothequecegep", "Bibliothèque cégep de l\'Outaouais"))
        self.pushButton_ajouter_doc.setText(_translate("Bibliothequecegep", "Ajouter un jeux"))
        self.pushButton_ajouter_abonner.setText(_translate("Bibliothequecegep", "Ajouter un livre"))
        self.pushButton_ajouter_doc_3.setText(_translate("Bibliothequecegep", "Ajouter un film"))
        self.lbl_biblio_2.setText(_translate("Bibliothequecegep", "Sélectionner l\'option voulue"))
        self.pushButton_ajouter_abonner_.setText(_translate("Bibliothequecegep", "Abonnement"))
        self.pushButton_ajouter_emprunt.setText(_translate("Bibliothequecegep", "Emprunt"))
